#!/bin/bash

tests="164.gzip  175.vpr  176.gcc  181.mcf  186.crafty  197.parser 256.bzip2"
LIMIT=1
DIR=$PWD

echo "testing $tests for $LIMIT runs"
for test in $tests
do
  cd "$test/src"
  export LOPT=""
  echo "">mem_vanilla.log
  echo "============================="
  echo "Building test $test "
  echo "============================="
  echo "Vanilla run"
  ./build_as_spec
  for ((a=1; a <= LIMIT ; a++)) 
  do
    vmstat 1 > mem_vanilla.log & ./build_as_spec | tee build.log
    sleep 2
    kill `pidof vmstat`
  done
  $DIR/count_mem.py mem_vanilla.log 1 $test
  export LOPT="-plugin-opt=lazy-loading"
  echo "">mem_lazy.log
  echo "============================="
  echo "Lazy run"
  for ((a=1; a <= LIMIT ; a++)) 
  do
    vmstat 1 > mem_lazy.log & ./build_as_spec | tee build.log
    sleep 2
    kill `pidof vmstat`
  done
  $DIR/count_mem.py mem_lazy.log 1 $test 
  echo
  cd $DIR
done

